/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sabri.entornos.ejercicios.Ejercicio7.mvcBD.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author rhtuf
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    public JCheckBox getDiarrea() {
        return Diarrea;
    }

    public void setDiarrea(JCheckBox Diarrea) {
        this.Diarrea = Diarrea;
    }

    public JCheckBox getDolor() {
        return Dolor;
    }

    public void setDolor(JCheckBox Dolor) {
        this.Dolor = Dolor;
    }

    public JButton getEnviar() {
        return Enviar;
    }

    public void setEnviar(JButton Enviar) {
        this.Enviar = Enviar;
    }

    public JCheckBox getFiebre() {
        return Fiebre;
    }

    public void setFiebre(JCheckBox Fiebre) {
        this.Fiebre = Fiebre;
    }

    public JCheckBox getOlfato() {
        return Olfato;
    }

    public void setOlfato(JCheckBox Olfato) {
        this.Olfato = Olfato;
    }

    public JCheckBox getTos() {
        return Tos;
    }

    public void setTos(JCheckBox Tos) {
        this.Tos = Tos;
    }

    public JLabel getCurso() {
        return Curso;
    }

    public void setCurso(JLabel Curso) {
        this.Curso = Curso;
    }

    public Integer getId() {
        return Integer.parseInt(Id.getText());
    }

    public void setId(JTextField Id) {
        this.Id = Id;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fiebre = new javax.swing.JCheckBox();
        Tos = new javax.swing.JCheckBox();
        Diarrea = new javax.swing.JCheckBox();
        Dolor = new javax.swing.JCheckBox();
        Olfato = new javax.swing.JCheckBox();
        Enviar = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        Curso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fiebre.setText("Fiebre");

        Tos.setText("Tos");

        Diarrea.setText("Diarrea");

        Dolor.setText("Dolor Muscular");

        Olfato.setText("Pérdida Olfato");

        Enviar.setText("Enviar");

        Curso.setText("Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Curso)
                        .addGap(18, 18, 18)
                        .addComponent(Id))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fiebre)
                        .addGap(18, 18, 18)
                        .addComponent(Tos)))
                .addGap(18, 18, 18)
                .addComponent(Diarrea)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Enviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Dolor)
                        .addGap(27, 27, 27)
                        .addComponent(Olfato)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Curso))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fiebre)
                    .addComponent(Tos)
                    .addComponent(Diarrea)
                    .addComponent(Dolor)
                    .addComponent(Olfato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(Enviar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Curso;
    private javax.swing.JCheckBox Diarrea;
    private javax.swing.JCheckBox Dolor;
    private javax.swing.JButton Enviar;
    private javax.swing.JCheckBox Fiebre;
    private javax.swing.JTextField Id;
    private javax.swing.JCheckBox Olfato;
    private javax.swing.JCheckBox Tos;
    // End of variables declaration//GEN-END:variables
}
