package com.sabri.ejercicios.encuesta;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

public class GUI_Encuesta_BD extends javax.swing.JFrame {
    
    public GUI_Resultados_BD ventanaResult; //ventana de resultados

    public static String urlBD = "jdbc:mysql://localhost:3306/encuestas";
    public static Connection con;

    public GUI_Encuesta_BD() {
        initComponents();
        setFrame();
    }

    public JRadioButton getjOpcion1() {
        return opcion1;
    }

    public JRadioButton getjOpcion2() {
        return opcion2;
    }

    public JRadioButton getjOpcion3() {
        return opcion3;
    }    

    private void setFrame() {
        this.setTitle("Encuestas BD");
        this.setMinimumSize(new Dimension(500, 240));
        this.setPreferredSize(new Dimension(500, 240));
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * Wopc3RNING: Do Nopc4T modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botonVotar = new javax.swing.JButton();
        botonResultados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        opcion1 = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel5 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        opcion2 = new javax.swing.JRadioButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel7 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        opcion3 = new javax.swing.JRadioButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encuesta");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        botonVotar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonVotar.setForeground(new java.awt.Color(255, 0, 51));
        botonVotar.setMnemonic('V');
        botonVotar.setText("Votar");
        botonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotarActionPerformed(evt);
            }
        });
        jPanel1.add(botonVotar);

        botonResultados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonResultados.setForeground(new java.awt.Color(255, 0, 51));
        botonResultados.setMnemonic('R');
        botonResultados.setText("Resultados de la encuesta");
        botonResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResultadosActionPerformed(evt);
            }
        });
        jPanel1.add(botonResultados);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Consideras adecuado la eliminación de mascarillas en interiores?");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 2, 2));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler5);

        buttonGroup1.add(opcion1);
        opcion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opcion1.setForeground(new java.awt.Color(51, 51, 0));
        opcion1.setText("Si");
        opcion1.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanel4.add(opcion1);
        jPanel4.add(filler2);

        jPanel3.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(filler3);

        buttonGroup1.add(opcion2);
        opcion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opcion2.setForeground(new java.awt.Color(51, 51, 0));
        opcion2.setText("No");
        opcion2.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanel5.add(opcion2);
        jPanel5.add(filler4);

        jPanel3.add(jPanel5);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));
        jPanel7.add(filler9);

        buttonGroup1.add(opcion3);
        opcion3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opcion3.setForeground(new java.awt.Color(51, 51, 0));
        opcion3.setText("NS / NC");
        opcion3.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanel7.add(opcion3);
        jPanel7.add(filler8);

        jPanel3.add(jPanel7);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTÓN VOTAR
    private void botonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotarActionPerformed
        if (this.buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Debes elegir una opción", "Información", JOptionPane.WARNING_MESSAGE);
        } else {         
            if (this.opcion1.isSelected()) {
                insertarBD(true, false, false);
            } else if (this.opcion2.isSelected()) {
                insertarBD(false, true, false);
            } else {
                insertarBD(false, false, true);
            }
        }
    }//GEN-LAST:event_botonVotarActionPerformed

    private void insertarBD(boolean y, boolean n, boolean ns) {

        try {
            String SQLInsert = "";

            if (y) {
                SQLInsert = "INSERT INTO respuestas (y) VALUES (1)";
            } else if (n) {
                SQLInsert = "INSERT INTO respuestas (n) VALUES (1)";
            } else if (ns) {
                SQLInsert = "INSERT INTO respuestas (ns) VALUES (1)";
            }

            conectarBD();
            PreparedStatement ps = con.prepareStatement(SQLInsert);
            int filas = ps.executeUpdate(SQLInsert);
            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Respuesta registrada. \nGracias por tu colaboración", "Ejemplo1-JDBC", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de BD", "Ejemplo1-JDBC", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            desconectarBD();
        }
    }

    //BOTÓN RESULTADOS 
    private void botonResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResultadosActionPerformed
        ventanaResult = new GUI_Resultados_BD(this, true);
        ventanaResult.setVisible(true);
    }//GEN-LAST:event_botonResultadosActionPerformed

    public static void conectarBD() {
        try {
            con = DriverManager.getConnection(urlBD, "root", "");
            System.out.println("Conexión realizada");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexion", "Ejemplo1-JDBC", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    public static void desconectarBD() {
        try {
            if (con != null) {
                con.close();
            }
            System.out.println("Desconextión realizada");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Encuesta_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Encuesta_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Encuesta_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Encuesta_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI_Encuesta_BD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonResultados;
    private javax.swing.JButton botonVotar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    private javax.swing.JRadioButton opcion3;
    // End of variables declaration//GEN-END:variables
}
