package com.sabri.ejercicios.encuesta;

import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public class GUI_Resultados_BD extends javax.swing.JDialog {

    private GUI_Encuesta_BD ventanaPpal; //referencia a la ventana inicial
    private double opc1; //nº de votos SI
    private double opc2; //nº de votos NO
    private double opc3; //nº de votos NS/NC  
    private double votos; //nº de votaciones    

    public GUI_Resultados_BD(GUI_Encuesta_BD v, boolean modal) {
        super(v, modal);
        initComponents();
        setFrame();
        setPanel();
        this.ventanaPpal = v;
        obtenerDatos();
        mostrarResumen();
    }

    private void setFrame() {
        this.setMinimumSize(new Dimension(420, 210));
        this.setPreferredSize(new Dimension(420, 210));
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(this.ventanaPpal);
    }

    private void setPanel() {
        this.jEditorPane1.setContentType("text/html");
    }

    private void mostrarResumen() {
        NumberFormat formateadorNum = NumberFormat.getPercentInstance(); //multiplica por 100 y añade %
        formateadorNum.setMaximumFractionDigits(2); //máximo 2 decimales
        DateTimeFormatter dtfDate = DateTimeFormatter.ISO_LOCAL_DATE;
        DateTimeFormatter dtfTime = DateTimeFormatter.ISO_LOCAL_TIME;

        double totalOpc1 = (votos == 0) ? 0 : opc1 / votos;
        double totalOpc2 = (votos == 0) ? 0 : opc2 / votos;
        double totalOpc3 = (votos == 0) ? 0 : opc3 / votos;

        LocalDate hoy = LocalDate.now();
        LocalTime ahora = LocalTime.now();
        this.jEditorPane1.setText(
                "<b>Fecha: " + dtfDate.format(hoy) + "</b><br>"
                + "<b>Hora: " + dtfTime.format(ahora) + "</b><br><br>"
                + this.ventanaPpal.getjOpcion1().getText() + " : " + formateadorNum.format(totalOpc1) + "<br>"
                + this.ventanaPpal.getjOpcion2().getText() + " : " + formateadorNum.format(totalOpc2) + "<br>"
                + this.ventanaPpal.getjOpcion3().getText() + " : " + formateadorNum.format(totalOpc3) + "<br><br>"
                + "<font size=\"14\" color=\"blue\">"
                + "<i>Gracias por tu colaboración!!</i>"
                + "</font><br>"
        );
    }

    private void obtenerDatos() {
        try {
            GUI_Encuesta_BD.conectarBD();
            String SQLSelect = "SELECT COUNT(*) FROM respuestas WHERE y=1 UNION ALL "
                    + "SELECT COUNT(*) FROM respuestas WHERE n=1 UNION ALL "
                    + "SELECT COUNT(*) FROM respuestas WHERE ns=1 UNION ALL "
                    + "SELECT COUNT(*) FROM respuestas";

            PreparedStatement ps = GUI_Encuesta_BD.con.prepareStatement(SQLSelect);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                this.opc1 = rs.getInt(1);
                System.out.println("opc1:   " + opc1);
                rs.next();
                this.opc2 = rs.getInt(1);
                System.out.println("opc2:   " + opc2);
                rs.next();
                this.opc3 = rs.getInt(1);
                System.out.println("opc3:   " + opc3);
                rs.next();
                this.votos = rs.getInt(1);
                System.out.println("TOAL VOTOS:   " + votos);
            }
            rs.close();

        } catch (SQLException ex) {

        } finally {
            GUI_Encuesta_BD.desconectarBD();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultados encuesta");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
