/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imagenes;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author vaqgalju
 */
public class Galeria extends javax.swing.JFrame {

    /**
     * Creates new form Galeria
     */
    public Galeria() {
        conectarBBDD();
        initComponents();
        //ImageIcon imageIcon = new ImageIcon("images/450_1000.jpg");
        //labelImagen.setIcon(imageIcon);
        retrieveImages();
        prueba(labelImagen);
    }
    private String urlDB = "jdbc:mysql://localhost:3306/images";
    private Connection c;
    private static ArrayList<String> imagesArray = new ArrayList<String>();
    
    private void conectarBBDD() {
        try {
            c = DriverManager.getConnection(urlDB, "root", "");
            System.out.println("Conectado");
        } catch (SQLException ex) {
            System.out.println("Error BBDD");
        }
    }
    
    public static void prueba(JLabel labelImages){
        int cont=0;
        while(cont<=imagesArray.size()){
            try {
                ImageIcon ii = new ImageIcon(imagesArray.get(cont));
                //labelImages.setIcon(ii);
                System.out.println(ii);
                Thread.sleep(1000);
                cont++;
                if (cont==imagesArray.size()) {
                    cont=0;         
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(Galeria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void retrieveImages(){
        try {
            String select = "SELECT path FROM images";
            PreparedStatement ps = c.prepareStatement(select);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                imagesArray.add(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Galeria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botonCargar = new javax.swing.JButton();
        cabecera = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCargar.setText("Cargar mas imagenes");
        getContentPane().add(botonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 306, 275, -1));

        cabecera.setBackground(new java.awt.Color(102, 255, 102));
        cabecera.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabecera.setText("Bienvenido al mundo Java");
        getContentPane().add(cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 275, 30));

        labelImagen.setText("jLabel3");
        getContentPane().add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 275, 210));

        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(10);
        jSlider2.setMinimum(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(2);
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargar;
    private javax.swing.JLabel cabecera;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JLabel labelImagen;
    // End of variables declaration//GEN-END:variables
}
